version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:1:compact,Topic2:1:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      APPLICATION_SECRET: letmein
      ZK_HOSTS: zookeeper:2181